# Generated by Django 5.2.6 on 2025-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(blank=True, max_length=120)),
                ('Actor2Name', models.CharField(blank=True, max_length=120)),
                ('DirectorName', models.CharField(blank=True, max_length=120)),
                ('MovieGenre', models.CharField(max_length=50)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
