# Generated by Django 5.2.6 on 2025-09-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='MovieGenre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Animation', 'Animation'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='ReleaseYear',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
